name: Code Review with ChatGPT

on:
  pull_request:
    branches:
      - main # 워크플로우가 실행되는 브랜치를 지정하세요.

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Code Review with ChatGPT
        id: code_review
        run: echo "::set-output name=review::$(node code_review.js)"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Add Code Review Comment
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const review = `Code Review 결과:\n${process.env.REVIEW}\n`;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: review
            });
        env:
          REVIEW: ${{ steps.code_review.outputs.review }}
